### ISSUE TITLE
Q: Adding a single struct entry to a map produces multiple changes

### ISSUE THREAD

**Issue by agis** [r3labs/diff#16]
Not sure if this is expected, but if so, you could consider this more of a question.

As the title says, when a map has an additional entry (entries are custom struct types), then instead of getting 1 `Change` when comparing the maps, I get N changes (where N=number of fields in the structs).

I have the following types:

```golang
type Product struct {
	ID             int `diff:"id,identifier"`
	Title          string
	Description    string
	BaseMaterials  map[MaterialID]bool
	ExtraMaterials []MaterialID
	Sizes          []SizeID
	Weight         int16
	Prices         map[SizeID]ProductPrice // also a struct type
	Type           TypeID
}

type Catalog struct {
  Products map[int]Product `diff:"products"`
}
```

And I'm trying to compare two catalogs, of which the one has one key missing from its `Catalog.Products` map. The following example demonstrates:

```golang
// assume we have catalog1 & catalog2, which are identical

// remove a single entry (Product) from catalog2.Products
delete(catalog2.Products, 2)

// and compare
changelog, _ := diff.Diff(catalog1, catalog2)
```

At this point, the changelog contains N `create` diffs, where N is the number of fields of the Product. All diffs are of type "from nil to something", since in catalog2 the product is not present at all.

What I actually need, is to get a single, compound diff with the new entry. Is that possible given the current implementation, or do I have to iterate over the changelog and manually inspect the diffs to combine them to a single one?

Thanks in advance.

**Comment by purehyperbole** [comment]
Hi there,

Thanks for raising the issue.

You're correct in that the library was designed to give an "itemised" list of all changes in something like a struct. So, when removing a struct it will list all fields of the struct as their own change.

It was handled this way to make parsing the output into something readable easier and I'm not sure how easy it will be to change without breaking things. 

As you mention, your best bet is going to be to iterate over the changelog and piece together what you need from that. There is a `Filter` method that returns only the changes for a given path, which might make that easier.

Sorry there isn't a more convenient way to handle this. If processing the output isn't an option, I can look at exposing an option to handle this a different way.

**Comment by agis** [comment]
Didn't know about `Filter`, thanks. It seems like it might help in my case (though I'm skeptical since it introduces another iteration on the changelog).

For now I'm processing the changelog and combining the changes manually. However it's not pretty, that's why I believe a new API (it doesn't have to break things) that does this would make sense in the package.

What I resort to is something like this:

```golang
for i := 0; i < len(changelog); i++ {
	ch := changelog[i]
	productAttrs := make(map[string]interface{})

	// product creations/deletions
	if ch.Type != "update" && ch.Path[0] == "products" {
		productID := ch.Path[1]

		for n := i + 1; n < len(changelog); n++ {
			ch2 := changelog[n]

			if ch.Path[0] != "products" ||
				ch2.Path[1] != productID ||
				ch.Type == "update" {
				break
			}

			if ch.Type == "create" {
				productAttrs[ch2.Path[2]] = ch2.To
			}

			i += n - i
		}
	}

	d, err := NewDiff(&ch, productAttrs)
	if err != nil {
		return nil, fmt.Errorf("error generating diffs from %#v: %s", ch, err)
	}

	diffs = append(diffs, d...)
}
```

It's pretty clunky from my point of view, that's why I think the library could handle it for users.

What do you think? I could help with deciding the API and implementing it.

**Comment by purehyperbole** [comment]
I agree, that's far from ideal! 

Having looked at the way structs are handled, it seems its possible to change this behaviour with an option.

Could you please take a look at the `struct-values-option` branch?

There is now an option called `DisableStructValues`. It should allow you to do something like:
```go
type Thing struct {
	Name string
	Type string
}

func main() {
	d, _ := diff.NewDiffer(diff.DisableStructValues())

	x := map[string]Thing{
		"1": {"John", "Person"},
		"2": {"Jack", "Person"},
	}

	y := map[string]Thing{
		"2": {"Jack", "Person"},
	}

	cl, err := d.Diff(x, y)
}
```

Which produces something like:
```json
[
    {
        "type": "delete",
        "path": [
            "1"
        ],
        "from": {
            "Name": "John",
            "Type": "Person"
        },
        "to": null
    }
]
```

**Comment by agis** [comment]
Seems great! I actually used a more complex example that's almost identical to my use case:

```golang
package main

import "fmt"
import "../../diff"

type Catalog struct {
	Products map[int]Product
}

type Product struct {
	ID            int `diff:"id,"identifier"`
	Title         string
	Materials     []int
	BaseMaterials map[int]bool
	Extras        []Extra
}

type Extra struct {
	Foo string
}

func main() {
	cat1 := Catalog{make(map[int]Product)}
	cat2 := Catalog{make(map[int]Product)}

	product := Product{
		ID:            35,
		Title:         "A shovel",
		Materials:     []int{5, 6, 1},
		BaseMaterials: map[int]bool{6: true},
		Extras:        []Extra{Extra{"baz"}},
	}

	cat2.Products[35] = product

	d, err := diff.NewDiffer(diff.DisableStructValues())
	if err != nil {
		panic(err)
	}

	cl, err := d.Diff(cat1, cat2)
	if err != nil {
		panic(err)
	}

	for _, change := range cl {
		p := change.To.(Product)

		fmt.Println("--------------")
		fmt.Println("action = " + change.Type)
		fmt.Printf("%#v\n", p)
		fmt.Println("--------------")
	}
}
```

And it outputs the following, which is exactly what I need:

```golang
--------------
action = create
main.Product{ID:35, Title:"A shovel", Materials:[]int{5, 6, 1}, BaseMaterials:map[int]bool{6:true}, Extras:[]main.Extra{main.Extra{Foo:"baz"}}}
--------------
```

**Comment by purehyperbole** [comment]
Awesome! I'll get this branch merged then. 

Thanks for the feedback :smile:

**Comment by agis** [comment]
Thanks a ton!
