### ISSUE TITLE
Add reflect.Invalid check to diffSlice

### ISSUE THREAD

**Issue by adrian-sturm** [r3labs/diff#25]
Currently, when diffing a slice type and a nil value, the diff() method returns an error "types do not match".
Inspecting your code i found that the diffSlice() method is missing the part at the beginning where you check if a or b are of type reflect.Invalid and thus there is a CREATE/DELETE change happening here.
This should be fairly easy to fix though, as you can just copy that part of logic from any other diff-method.
Thanks in advance! :)

**Comment by purehyperbole** [comment]
Hey, thanks for raising the issue. This should now be fixed on the master branch.
