### ISSUE TITLE
Recommended compatibility with json tag

### ISSUE THREAD

**Issue by js2854** [r3labs/diff#31]
It is recommended to be compatible with json tag or support custom tag

**Comment by purehyperbole** [comment]
Could you please test out the `custom-diff-tag` branch? It allows you to specify:

```go
d, err := diff.NewDiffer(diff.DiffTag("json"))
if err != nil {
    ...
}

cl, err :=d.Diff(a, b)
```

**Comment by js2854** [comment]
> Could you please test out the `custom-diff-tag` branch? It allows you to specify:
> 
> ```go
> d, err := diff.NewDiffer(diff.TagName("json"))
> if err != nil {
>     ...
> }
> 
> cl, err := d.Diff(a, b)
> ```

Thank you very much. I tested it. No problem.
