### ISSUE TITLE
Diff of slices with the same items

### ISSUE THREAD

**Issue by sunsingerus** [r3labs/diff#6]
When I am trying to diff two slices with different number of items, but repetitive item values, I've got `nil` as a `Diff()` result, while those slices are not the same - they have different number of items.
Min example:
```
	a := []int{1, 1}
	b := []int{1}
	changelog, err := diff.Diff(a, b)
```
will produce `nil`,`nil` as a result - no changes, no errors, while `a` has different number of items than `b` and is **different**
It looks reasonable to have one change log entry of `Type: "delete"` in this case. Yes, it is impossible to say what is the index of deleted item - `0` or `1`, but any of them (0 or 1) will perfectly do and indicate the difference.
Can you, please, advice on how to handle this correctly?

**Comment by purehyperbole** [comment]
Thanks for the report. I'm looking into fixing this now.

**Comment by purehyperbole** [comment]
Hi, 

I've implemented a fix on the `slice-duplicates` branch and added a test case. 

If possible, could you please try this branch and see if it fixes your issue? 

Thanks
