### ISSUE TITLE
Exclude a field or path from diff

### ISSUE THREAD

**Issue by saul-data** [r3labs/diff#65]
I couldn't find anything in the documentation but it would be really useful to exclude specific fields or paths in the struct from output change log.

**Comment by purehyperbole** [comment]
Hey @saul-gush 

Not sure if this is what you're looking for, but you can use the `-` option in a tag to exclude fields from a struct.

```go
type MyStruct struct {
    Excluded string `diff:"-"`
    Included int
}

a := MyStruct{
    Excluded: "this will not be in the changelog",
    Included: 5,
}

b := MyStruct {
    Excluded: "changed",
    Included: 8,
}

cl, err := diff.Diff(a, b)
// returns only the change from 5 -> 8
```

**Comment by saul-gush** [comment]
@purehyperbole That worked perfectly thank you! I think others would find it useful, is it in the documentation anywhere?

**Comment by purehyperbole** [comment]
@saul-gush Awesome! 

Yes, it's under the [tags](https://github.com/r3labs/diff#tags) section in the main README, although it may not be all that visible if you are using another means of viewing documentation.

**Comment by saul-gush** [comment]
Ohhhh that makes sense. I may have misread that part of the documentation. I found your example above to be more articulate/user friendly :)
