### ISSUE TITLE
Error with update change

### ISSUE THREAD

**Issue by cartrujillo** [r3labs/diff#9]
When I have two slices with two changes (update and create) the changelogs returned is not what it is expected. The example is:

I have two slices like these:
`a := []map[string]interface{}{
		{
			"name": "name1",
			"type": []string{"null", "string"},
		},
	}`

	
`b := []map[string]interface{}{
		{
			"name": "name1",
			"type": []string{"null", "int"},
		},
		{
			"name": "name2",
			"type": []string{"null", "string"},
		},
	}`

`changelog, _ := diff.Diff(a, b)`

The changelog is:

`[{create [0 type 1] <nil> int} {create [1 name] <nil> name2} {create [1 type] <nil> [null string]}]`

But the expected result is:

`[{update [0 type 1] string int} {create [1 name] <nil> name2} {create [1 type] <nil> [null string]}]`

I saw that in the diff_map.go file there is a function called swapChange that does the change from "update" to "create". Maybe here is the problem.

Thank you very much.

**Comment by purehyperbole** [comment]
I've just tried using the examples you provided and this used to be the old behaviour. Not sure exactly whats changed, but it seems to be related to the changes in #8. Trying with a version before that commit seems to work as per your expectations. 

I'll try and write some test cases and see if i can come up with a fix that addresses both issues.

**Comment by purehyperbole** [comment]
Looks like you were correct, swapChange was actually the piece that was causing the issue. 

I've implemented the fix on the `swap-changes-fix` branch, could you give it a test please and let me know if it resolves your issue?

**Comment by cartrujillo** [comment]
Yes, it works now! :+1:

**Comment by purehyperbole** [comment]
awesome, thanks for the feedback :smile:
